### ISSUE TITLE
An unbounded naming chaos

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#100]
**Naming mess**
Take the following overview of methods I came across while working on issue #99. Many names are used interchangeably for similar concepts.

|Type|Class|Method|
|---|---|---|
|~`PolyLine2d`~`Polygon2d`|`LocatedObject`|~`.getGeometry()`~`getContour()`|
|~`List<Point2d>`~`Polygon2d`|`ConflictData`|`.getContour()`|
|`Polygon2d`|`SpatialObject`|~`.getShape()`~`getContour()`|
|`Polygon2d`|`DynamicSpatialObject`|~`.getShape(Time)`~`getContour(Time)`|
|~`PolyLine2d`~`Polygon2d`|`TrafficLightDetectorData`|~`.getGeometry()`~`getContour()`|
|`Bounds2d`|`OtsLine2d`|~`.getEnvelope()`~|
|`Bounds`|`Locatable`|`.getBounds()`|
|~`OtsBounds2d`~`Bounds2d`|`OtsLocatable`|`.getBounds()`|
|`Polygon2d`|`Node`|~`.getShape()`~`getContour()`|

**What we need**
We have several names for what seems to be the same: geometry, envelope, contour, shape and bounds.

There are good arguments to distinguish three functionally different definitions:
1. Geometry that defines where an object is in space, including its dimensionality (i.e. not just a point).
- This can be used to check overlap between two non simple objects.
- This is used to know where to animate objects.
2. Geometry that defines the shape of an object, regardless of its position.
- For moving objects this is a necessity to determine 1.
- This allows formulations that are quicker to compute. 
  - For example, is a point within a rectangle? By transforming the point to the coordinate system of the shape, this becomes a very simple abs(x)<dx and abs(y)<dy check.
  - Note that this is much more efficient than transforming some geometry regarding a location (going from 2 to 1), and then checking whether the point is within this generalized geometry.
  - Similarly, signed distance functions (negative values inside the object) can be computed quickly. See <a href="https://iquilezles.org/articles/distfunctions/">here</a>. These functions are required for spatial calculations for example regarding visibility.
3. Geometry that can be used _quickly_ to filter many objects that are certainly not overlapping/not in need to animate/etc., wherever they may be.

**What terms to use for which?**
_~~Geometry~~_: this is too broad of a term to specify what we mean.
_~~Envelope~~_: this is a very specific mathematical term regarding a family of curves. This is not what we mean.
_Contour_: this defines the edge of an object, and is a suitable term for function **1**.
_Shape_: this seems a good fit for function **2**, as the shape of an object does not change just because it moves.
_Bounds_: this seems a good fit for function **3**, as bounds are generally perceived as min/max along a number of dimensions.

With locations given as `OrientedPoint2d`, this gives the following relationships:
_Shape_ + _Location_ = _Contour_
_Bounds_ + _Location_ = _Bounds_ (possibly bigger due to ration)

**What types are suitable?**
_Contour_
For the most general case, this is a `PolyLine2d` as some objects are lines without width. Note that point objects have no contour or shape, only a location (although possibly expanded to some shape for clickability). More specific classes can specify `Polygon2d` as output, which extends `PolyLine2d`.

_Shape_
Being defined relative to its origin, the contract with a shape is different from a contour. For example, in a `contains(Point2d)` method, the shape assumes the point to be translated to its own coordinate system. The origin does not need to be part of the shape (e.g. a donut). A shape can also be used for signed distance functions, which a `PolyLine2d` or `Polygon2d` do not have. Hence, a new class `Shape` is required, with two specific methods:
- `Polygon2d asPolygon()`
- `double signedDistance(Point2d)`

_Bounds_
`Bounds2d` from DJUTILS fits this function perfectly, and is used as such in DSOL. 

**What this gives**
As the functions share much functionality, it is logical for them to have an inheritance relationship.

`interface org.djutils.draw.bounds.Bounds<?, ?, ?>` (DJUTILS)
- min/max x
- min/max y
- `contains(Point)`, `covers(Point)`
- `contains(Drawable)`, `covers(Drawable)`, `disjoint(Drawable)`: **suggest removal**, we cannot know whether the drawable is contained/covered, as it may be a line or a polygon. That is, the closing segment of a polygon may go outside bounds. E.g. the centerline of a U, is not contained in U if it defines a polygon. We can cover the cases for polyline and polygon as we know, but more sub-classes can be defined. The current implementation in e.g. `Bounds2d` just takes the `Bounds2d` of the input drawable, which tells you little on the actual shape.
- `intersects`/`intersection(Bounds)`: these methods only make sense for bounding boxes (as bounds are intended). However, to allow bounds to be extended by more complicated shapes that also serve as bounds (the first three bullets), they are **suggested to be moved** to `BoxBounds`.

`interface org.djutils.draw.bounds.BoxBounds<?, ?, ?> extends Bounds` (DJUTILS, new)
- `intersects`/`intersection(Bounds)`: see last bullet at `Bounds`.

`class org.djutils.draw.bounds.Bounds2 implements BoxBounds` (DJUTILS)

`interface Shape extends Bounds` (OTS, currently called `OtsBounds2d`)
- `Polygon2d asPolygon()`
- `double signedDistance(Point2d)`
- With implementations `BoundingBox`, `BoundingBoxRounded`, `BoundingCircle`, `BoundingPolygon` and `BoundingRectangle`. Possibly renamed to `BoxShape` etc.
- Implementations have fast implementations of `contains` etc.
- Note: `BoxShape` is a shape around the origin, `BoxBounds` are just min/max of wherever the object is.
- Note: `BoundingRectangle` does not have the origin at its center (and is currently also used therefore as bounds at an actual location not containing the origin for compatibility in the current structure).

`interface OtsLocatable extends Locatable` (OTS)
- `Point2d getLocation()`: specifies point type. Can be `DirectedPoint2d` for sub types.
- `OtsBounds2d getBounds()`: **suggested to be replaced** by the following two.
- `default Bounds<?,?,?> getBounds() {return getShape();}`: defined by `Locatable` as the bounds around the origin. Note that `Shape` extends `Bounds`.
- `Shape getShape()`
- Note: some sub types add a contour through various names. This may need to be harmonized by letting them implement/extend an interface that has `PolyLine2d getContour()`, possibly specified in implementations to `Polygon2d getContour()`. Perhaps `LocatedObject` is suitable for this.

**Comment by Peter-Knoppers** [comment]
There are several of methods that return information about the contour of an object in various forms and under various names. I believe that everthing that returns a contour should be named getContour() and all should return a Polygon2d (but a point object won't be able to comply). Some OTS objects can move around in 2D space. These may warrant a getContour method that takes a Time parameter, an OrientedPoint2d, or a Transform2d. It is debatable whether such a getContour method should have a different name.

Interface LocatedObject species a method getGeometry that returns a PolyLine2d.
The method name should be getContour() and return a Polygon2d.

Interface ConfictData specifies a method getShape() that returns a List<Point2d>.
The method name should be getContour() and return a Polygon2d.

Interface SpatialObject specifies a method getShape() that returns a Polygon2d.
The method name should be getContour().

Interface DynamicSpatialObject specifies a method getShape() that returns a Polygon2d.
The result of this method applies the transformation implied by the getLocation() method to obtain a time-dependent result.
This could also be achieved by specifying that getShape() takes a DirectedPoint argument, or a Time argument.
The method getShape may be renamed getContour.

Interface TrafficLightDetectorData specifies a method getGeometry that returns a PolyLine2d.
This method should be named getContour() and return a Polygon2d.

Class OtsLine2d adds and often duplicates things compared to djutils-draw Line2d like
- lengthIndexedLine (duplicate)
- projectOrthogonal (duplicate?)
- intersectionOfLines (very similar to djutils-draw Point2d.intersectionofLines)
and some methods that take a Length parameter of return a Length value.
It appears to me that OtsLine2d should extend Line2d; not wrap it.

OtsLine2d has a method getEnvelope that returns the Bounds2d object of the wrapped PolyLine2d.
This method should be named getBounds.

Class Node contains a method getShape() that returns a Polygon2d shaped like a 1m square, centered on the Node.
This method should be named getContour, and even then it is a bit of a disaster.

Concerning a signedDistance method for Polygon2d. I believe that implementing this may be quite complex for arbitrary Polygons (which may be self-intersecting).

The contains(), intersects() and disjoint()  methods in djutils-draw only compare the bounding boxes of the objects. Maybe this should be documented more clearly.

PK

**Comment by WJSchakel** [comment]
I agree Peter, although I'm not yet fully sure what to do with line objects (e.g. traffic lights) and nodes regarding `Polygon2d getCountour()`.

I can explore whether `OtsLine2d` can extend `PolyLine2d`. Some functionality still seems duplicate indeed.

Signed distance for a polygon is quite easy actually (though not cheap):

```java
double dist = asPolygon().closestPointOnPolyLine(point).distance(point);
return asPolygon().contains(point) ? -dist : dist;
```

The `contains()`, `covers()` and `disjoint()` methods in djutils-draw should I believe not have a `Drawable` as input, but another `Bounds` object.

**Comment by WJSchakel** [comment]
# Proposed changes on OTS #

Regarding being in world coordinates or relative to position, instead of defining what contour/bounds/shape would mean, I propose we make clear what methods provide. Then still, the output of these methods can be translated and rotated, like DSOL does with object bounds. So I propose:
- We use `getContour()` for the numerical actual shape in world coordinates.
- We use `getBounds()` for the bounding box relative to the location, as expected by DSOL.
- We use `getShape()` for signed distance in fast numerical or continuous implementations, relative to the location.

Note that signed distance is required for efficient visibility algorithms. There is overlap between the bounds and shape, but I do not want to merge these objects. A bounding box can perform calculations such as `B3 = B1.intersection(B2)`, which arbitrary shapes cannot. There is possible overlap between the shape and the _internal_ non-translated polygon for the contour. This can be solved efficiently internally per object type (i.e. one uses the other, see _Based on contour_ and _Based on shape_ below).

There are various interfaces in the spatial realm, e.g. for animation or for spatial trees. Let's harmonize them according to the above. The inheritence I propose is:

**Spatial trees / shape for drawing**

`SpatialObject`
- `Polygon2d getContour()`; Relative to world; contour defines actual shape at location

`DynamicSpatialObject` extends `SpatialObject`
- `Polygon2s getContour(Time)`

**Fast filtering / DSOL**

`OtsLocatable implements SpatialObject`
- `Point2d getLocation()`; Sub-classes can define `OrientedPoint2d`
- `Bounds2d getBounds()`; Relative to location; bounds define a bounding box (min/max)

**Geometric object properties**

`LocatedObject extends OtsLocatable`
- `Length getHeight()`
- `String getFullId()`
- `OtsShape getShape()`; Relative to location

`LaneBasedObject extends LocatedObject`
- `Lane getLane()`
- `Length getLongitudinalPosition()`
- `Length getLength()`

**Visibility**

`OtsShape` is a new interface that defines:
- `Length signedDistance(Point2d)`
- `boolean contains(Point2d)`
- `double minX/Y()`
- `double maxX/Y()`
- `Polygon2d asPolygon()

With these methods objects become suitable to e.g. implement visibility in models.
There are now two ways to define both a shape and countour.

_Based on contour_
Current objects have an internal `Polygon2d`. This can be used to create a `PolygonShape`.
All default methods of `OtsShape` can be based on `asPolygon()`. No additional work is required for the object to be seen as an `OtsShape`.

_Based on shape_
Objects with simpler shapes can use e.g. `RectangleShape`, which work much faster.
Then `getCountour()` could use `getShape().asPolygon()` translated/rotated by `getLocation()`.

**Other changes**
`Gtu` should implement `LocatedObject` so `GTU` can interact in visibility.
`LaneBasedGtu` should implement `LaneBasedObject`, this aides perception that considers objects and GTUs.

Furthermore I want to remove `Drawable` (the OTS version). Nothing uses it, except some fixed-color colorers that do not even use the object to determine the color.

**Comment by WJSchakel** [comment]
What started as renaming and cleaning up `BoundingXXX` classes to `XXXShape` in ots-base, escalated nessecarily to doing much more. This is because these classes implemented `OtsBounds2d` which extended `Bounds`. That is, these classes were used to provide the bounds of various simulation objects. But as described above, `Shape` and bounds should not be hybrid. A move was made towards just using `Bounds2d`, but that lacks shapes more complicated than a rectangle. Hence, `OtsLocatable` was made to extend `SpatialObject`, with renamed method `getContour()`, and the various object classes were changed accordingly to provide a `Polygon2d` contour. Next, due to different uses of world coordinates vs. relative to position, transforms were applied where needed between bounds and geometry in both the object classes and the classes that provide data for their animation. After some work, animation is correct and objects do not disappear due to erroneous bounds.

In many object constructors of sub classes of `OtsLocatable`, `OtsLocatable.asBounds(this)` is used after the location and contour are set, to derive bounds for the object.

`AbstractLaneBasedObject` has constructors with `PolyLine2d` to represent the line, and optionally a `Polygon2d` for the contour. The line is used to trigger detectors. The contour is there to comply to the superclass `LocatedObject`. If no contour is provided, one is created from the line. Only `Conflict` is created with a dedicated contour to draw the area.

`AnimationGtuGeneratorPositionData` and `AnimationSpeedSignData` will throw a `UnsupportedOperationException` in `getContour()` as these objects are essentially point objects. The animation should not need a contour.

**Comment by WJSchakel** [comment]
`ClickableBounds` was moved from ots-base to ots-draw. It is now only used in the animation data objects in ots-animation, the data objects for animation in the editor in ots-editor, and in `CenterLineAnimation` for lanes in ots-base. The simulation objects themselves do not use `ClickableBounds` for their bounds.

**Comment by WJSchakel** [comment]
`OtsLocatable.asPolygon()` renamed to `OtsLocatable.boundsAsContour()`.
`OtsLocatable.asBounds()` renamed to `OtsLocatable.contourAsBounds()`.
Added `OtsLocatable.relativeContour()` which transforms the contour to be relative to the location.
Removed `DynamicSpatialObject.transformShape()` but added `OtsLocatable.transformContour()`.
Removed `PolygonShape.geometryToBounds` as it is no longer used.

All these static methods in `OtsLocatable` forward to each other where a single private method actually performs transformation.

**Comment by WJSchakel** [comment]
`OtsLine2d.getEnvelope()` is removed. Table at start of this issue is updated with relevant method name changes and output type changes.

**Comment by WJSchakel** [comment]
Separating `Shape` from `Bounds` has undone the solution for issue #99. We need a `Bounds2d` implementation that has a `contains(Point2d)` method that uses the actual shape of the object relative to its location. The users can click on the shape of objects, rather than their rectangular bounds.

**Comment by WJSchakel** [comment]
`ClickableBounds` has been removed. Instead, data interfaces for animation now all implement `ClickableLocatable` which itself extends `OtsLocatable`. Many implementation of the `getBounds()` method, which used `ClickableBounds` with the bounds of an underlying object, have been removed. The bounds are automatically derived by using the shape. The shape is also used to accurately check whether a click is on the object, with a minimum expanse of 2x2m.

`OtsLocatable` by default implements `getShape()` as below. This transforms the contour and creates a new shape on every call. Sub-classes can store a shape instead and return it. This is done by `CrossSectionElement`, `Link`, `Node`, `StaticObject` and `Gtu`.

```java
    default OtsShape getShape()
    {
        return new PolygonShape(relativeContour(this));
    }
```

For now this all works with `PolygonShape` except for `Gtu` which uses `OffsetRectangleShape`. **For thin objects at an angle the logic of `ClickableLocatable` needs to be amended (perhaps in a sub-interface for line objects), as the x and y range are then large enough, but the shape itself will not see points as contained.**

**Comment by WJSchakel** [comment]
`ClickableLocatable` is extended by `ClickableLineLocatable` which returns bounds that see a point within 1m of the line as contained. This is implemented by line data objects such as links, lane center lines and lane-based objects.

The shape is now also cached by `AnimationLinkData`, `AnimationConflictData`, `AnimationLaneBasedObjectData`. **For certain editor animation data this is not yet done.**

`CrossSectionElementData` and `StripeData` make explicit that `getCenterLine()` returns the center line in world coordinates. `ClickableLineLocatable`  makes explicit that `getLine()` returns the object line in object coordinates (regardless of whether its a center line or a lane-based object line). This also holds for the new method `LaneBasedObject.getLine()` which supports the line for animation during simulation.

`OtsLocatable.transformLine(PolyLine2d, Point2d)` was added to support obtaining a line in object coordinates.

**Comment by WJSchakel** [comment]
Made `LinkData` extend `ClickableLineLocatable`.

Cached shape in `LaneAnimation.CenterLine`, `MapCrossSectionData`, `MapLaneBasedObjectData`, `MapNodeData` and `MapPriorityData`.

**Comment by WJSchakel** [comment]
Besides `Drawable` also `FixedColorer` was removed as nothing used it.

**Comment by WJSchakel** [comment]
(commit above says `OtsLocatable` but that should be `LaneBasedObject`)

`OtsLocatable` replaced with `LaneBasedObject` in `Estimation`, `HeadwayGtuType` and perception iterables (and subtypes).

Added `ClickablePointLocatable` for nodes.

**Comment by WJSchakel** [comment]
The final open point about `OtsLine2d` is made in to a separate issue #151. 

All changes made for this issue were on OTS side. Regarding how DSOL is used there remains a conceptual question. As it is currently, both DSOL and OTS used `Bounds` as though they are rectangles. Conceptually they may be more complicated shapes. There are two choices:
1. Formally define `Bounds` as rectangles, and consider whether methods such as `contains`, `covers` and `disjoint` are still sensible and based on the right input types. If not, they could perhaps be dropped.
2. Formally define `Bounds` as any shape, causing the concepts of `Bounds` and `OtsShape` to have to be merged. In this case, certain methods such as `Bounds intersection(Bounds)` need to be dropped as no one is going to implement finding the intersection between arbitrary shapes. Moreover, this is ill defined as overlap between two shapes may be multiple areas.
