### ISSUE TITLE
Rename acronyms to camelcase

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#11]
OTS, OD, EGTF, ACC, CACC, ASM, TrafCOD, XML, etc.

**Comment by averbraeck** [comment]
Renamed all classes in all projects. There might still be inner classes that have not yet been converted. We can convert them when we encounter one of the classes. The comments that point to the classes (e.g., a class javadoc descriptor) might still mention the old class name. A separate issue has been opened (Issue #17) to make the comments consistent.

For now, this issue about the renaming of the class names is closed.
