### ISSUE TITLE
Detector and DetectorType to replace Sensor

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#12]
The term "Sensor" is often used to describe devices in e.g., a car and the term "Detector" is often used to denote objects in the infrastructure that detect GTUs. In OTS we currently use the term Sensor for the infrastructure elemets. It would be better to rename all these classes to use the term Detector instead.

**Comment by WJSchakel** [comment]
- Created `DetectorType`.
- Removed `Compatibility` and with it some constructors using Compatibility.EVERYTHING.
- Created the following detector types in `DefaultsRoadNl`: `ROAD_USERS`, `VEHICLES`, `LOOP_DETECTOR` and `TRAFFIC_LIGHT`.
