### ISSUE TITLE
Create NodeType class

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#14]
With isCentroid() method that gives false by default.

**Comment by averbraeck** [comment]
A NodeType class has been created, with a new way of implementing the DEFAULTS (Issue #8). The Centroid has been introduced as a separate class that does not accept links that are not of type CONNECTOR. 

One task remains: registering the NodeTypes in the Network.

**Comment by WJSchakel** [comment]
> One task remains: registering the NodeTypes in the Network.

As discussed in issue #8, types will no longer be registered in the network.
