### ISSUE TITLE
Suppress warnings/infos in generated files

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#152]
In `org.opentrafficsim.xml.generated` files are generated based on our XML specification (XSD). Currently these files create 5530 warnings and infos as compile time warnings and checkstyle warnings. It would be great if we can suppress them.

**Comment by WJSchakel** [comment]
In the pom file of ots-parser-xml we have a plugin to generate the code. By adding a replace plugin, each class and enum gets annotated with `@SuppressWarnings("all")`.

The `process-sources` phase does give a warning: _Plugin execution not covered by lifecycle configuration_. It does work however. I've tried other phases but those either had the same warning and result, or did not work.

```xml
      <plugin>
        <groupId>com.google.code.maven-replacer-plugin</groupId>
        <artifactId>replacer</artifactId>
        <version>1.5.3</version>
        <executions>
          <execution>
            <phase>process-sources</phase>
            <goals>
              <goal>replace</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <includes>
            <include>${project.basedir}/src/main/java/org/opentrafficsim/xml/generated/*.java</include>
          </includes>
          <regex>true</regex>
          <regexFlags>
            <regexFlag>MULTILINE</regexFlag>
          </regexFlags>
          <replacements>
            <replacement>
              <token>^public class </token>
              <value>@SuppressWarnings("all") public class </value>
            </replacement>
            <replacement>
              <token>^public enum </token>
              <value>@SuppressWarnings("all") public enum </value>
            </replacement>
          </replacements>
        </config
```

**Comment by WJSchakel** [comment]
A few warnings remain due to file lengths. To suppress these I've added the folder to be ignored in checkstyle: 

Project properties > Checkstyle > Exclude from checking... > files from packages

Using the 'Change...' button the generated sources package can be selected. The result of both the plugin and this is that the package shows no warnings at all.

**Comment by WJSchakel** [comment]
Changed the first replacement to what is below as jaxb may also produce abstract classes.

```
            <replacement>
              <token>^public( abstract)? class </token>
              <value>@SuppressWarnings("all") public$1 class </value>
            </replacement>
```

**Comment by averbraeck** [comment]
Used these settings both in ots-xml and ots-opendrive. No warnings in the generated code for now.
