### ISSUE TITLE
Remove direction / directionality from XML format

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#16]
The XML format still contains references to DIRECTION in the format. The parser does not process it anymore, but the XSD files and XML files for the examples and unit tests need to be adapted.

**Comment by WJSchakel** [comment]
`Direction` was changed to `Compatible`, a `boolean` field that is `true` by default. When `true`, the GTU type is added as a compatible GTU type. Otherwise, the GTU type is added as a specific incompatible GTU type.
