### ISSUE TITLE
Make class names in comments consistent with refactoring

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#17]
Several types of refactoring of code have been carried out.

- removal of GTUDirectionality, LongitudinalDirectionality, LinkDirection, and LaneDirection classes
- renaming of class DirectedLinkPosition to LinkPosition
- renaming of DirectedLanePosition to LanePosition
- renaming of methods that had the word 'Directed' or 'Direction'
- renaming of classes with all caps acronyms to camel case acronyms (XML -> Xml, OTS -> Ots, DEVS -> Devs, etc.). 

Comments have not yet been adapted to this refactoring in many places in the code. It is important to make this consistent.

**Comment by WJSchakel** [comment]
Directed and Direction mainly matched: `DirectedPoint`, `DirectedSimpleWeightedGraph`, `Directed{LaneChangeModel}`, `Direction` and `LateralDirectionality`. These were not changed.

Many other changes were made, both in code and the comments, among which: WGS84/RD, 2D/3D, OTSShape/OTS2DSet, XY.
