### ISSUE TITLE
Rename ots-parser-xml project to ots-xml

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#173]
There will be more parser projects, but the `ots-xml` project is the central one for OTS. It might do more with other parsers and translators, such as writing XML or making transformations. Therefore, the more generic name `ots-xml` will be used for the project from now on.

**Comment by WJSchakel** [comment]
In my head is was mostly just a more concise name. Suppose we have `ots-opendrive`. Then I would assume any importing/exporting code from/to OpenDRIVE is within the `ots-opendrive` project. Then, `ots-xml` can just remain focused on our own xml. Dependency would then be one-way: `ots-opendrive` depends on `ots-xml`.

The same would hold for any other parser that allows translation to/from `ots-xml`.

**Comment by averbraeck** [comment]
Good point. Will do.

**Comment by averbraeck** [comment]
Completed and working in Eclipse.
