### ISSUE TITLE
Add ots-opendrive project

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#174]
Projects related to ots use the OpenDrive format to specify the network. A parser for OpenDrive that translates the network to our internal XML format would therefore be very useful. The intended name for the project is `ots-xml-opendrive`, since it is **only** concerned with the parsing of OpenDrive XML to the OTS XML format.

**Comment by WJSchakel** [comment]
I can imagine that in the future we might also support OpenSCENARIO, in which vehicle movements are specified for scenarios. Its static content is based on OpenDRIVE. For now I'm fine with only focussing on OpenDRIVE. In the spirit of short names, why not use `ots-opendrive`? Is your concern that this may lead people to think we e.g. have an OpenDRIVE editor or other features around OpenDRIVE we do not have?

**Comment by averbraeck** [comment]
It's a good idea to use the project name ots-opendrive. We might add more functions to the project later on. For now, it concentrates on XML transformation to the OTS internal XML format.

**Comment by averbraeck** [comment]
First we need to do a check if we can have a public project that parses OpenDrive files. The license terms state: "The research and education communities as well as other licensees are not entitled to pass standards on to third parties". OpenDrive **is** the standard. If it cannot be shared or used by others, it is not possible to include any OpenDrive parsing in our project.

**Comment by averbraeck** [comment]
The license terms to the OpenDrive standard state: "In alteration to the regular [license terms](https://www.asam.net/license), ASAM allows unrestricted distribution of this standard. §2 (1) of ASAM’s regular [license terms](https://www.asam.net/license) is therefore substituted by the following clause: "The licensor grants everyone a basic, non-exclusive and unlimited license to use the standard ASAM OpenDRIVE". This means that the OpenDrive parser is allowed under the license terms of the standard.
