### ISSUE TITLE
Research cloning of non-serializable objects using the xml Cloner

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#175]
Right now, the unit types in XML, such as the `LengthType` cannot be cloned due to the field:

```java
private static final Function<Object, Length> TO_TYPE = 
    (o) -> Length.instantiateSI(((Number) o).doubleValue());
```

The serialization gives an exception:

```
Exception in thread "main" java.io.NotSerializableException: 
    org.opentrafficsim.xml.bindings.types.LengthType$1
```

**Comment by averbraeck** [comment]
A first analysis shows that providing a `readObject` and `writeObject` method that does not read/write the `Function` field does **not** make any difference. The exception is still thrown.

**Comment by averbraeck** [comment]
The rules for a class being Serializable in Java are as follows:
- The class must implement the java.io.Serializable interface.
- All of the fields in the class must be serializable. If a field is not serializable, it must be marked transient.

So, it seems there are two solutions:
1. Make the field **serializable**. One way to do that is by defining: a new type `SerializableFunction<T, R>` where this class extends `Function<T,R> & Serializable`. A first tests shows that that works, and it is entirely risk-free.
2. Make the field **transient**. Since the lambda function is (by definition) stateless, making it transient might work as well. In this case, the non-serializable field is `static final`, so no new instances of the `LengthType$1` object need to be generated anyhow in the `Cloner`. A bit more research on `transient` might help to understand what risks we have when making a `static final` lambda function `transient`.

**Comment by WJSchakel** [comment]
I think static fields are not relevant for serialization. However, the static field is used as input to the constructor towards the superclass `ExpressionType`, which stores it as a property. It would be property `ExpressionType.toType` that would need to be transient. As mentioned in issue #172, for the particular issue, we use an abstract method rather than a `Function`.

**Comment by averbraeck** [comment]
I tested the following method:

```
protected static final transient Function<Object, String> TO_TYPE = 
    (o) -> String.valueOf(((Number) o).doubleValue());
```

And then writing with an `ObjectOutputStream` followed by reading with an `ObjectInputStream`. Clones perfectly. The lambda expression afterward works without problems. In other words, the class `LengthType$1` is created. No more errors. Therefore, this would be my preferred option for a stateless static function!

**Comment by averbraeck** [comment]
By the way, the following also works perfectly:

```
static interface SerializableFunction<T, R> extends Function<T, R>, Serializable  {  }
protected static final SerializableFunction<Object, String> TO_TYPE = 
    (o) -> String.valueOf(((Number) o).doubleValue());
```

So, if that is to be preferred, it can also be used.

**Comment by averbraeck** [comment]
(note that the above comes from my own test code -- that's why the function is protected and returns a String).

**Comment by averbraeck** [comment]
> I think static fields are not relevant for serialization. 
Indeed. It does not make a difference whether it is static or not, stateless or not, final or not. 

> However, the static field is used as input to the constructor towards the superclass `ExpressionType`, which stores it as a property.
Indeed, both the function itself and the field in the `ExpressionType` could be made transient, **but then the field in ExpressionType will not be initialized when deserializing**. In case you store the function, a `SerializableFunction` would be the best option in my opinion.

**Comment by averbraeck** [comment]
Another reason can be (see https://stackoverflow.com/questions/38018415/how-to-safely-serialize-a-lambda) that a **non-static** lambda function can have a pointer to `this`. That can refer to your entire XML-parser and lots of other stuff, which means that you might serialize everything in memory. 

The same post points to the fact that `SerializedLambda` (which happens when you make a lambda function `Serializable`) is perfectly defined: https://docs.oracle.com/javase/8/docs/api/?java/lang/invoke/SerializedLambda.html. This article explains what happens under the hood: https://www.baeldung.com/java-serialize-lambda.

**Comment by WJSchakel** [comment]
> Another reason can be (see https://stackoverflow.com/questions/38018415/how-to-safely-serialize-a-lambda) that a **non-static** lambda function can have a pointer to `this`. That can refer to your entire XML-parser and lots of other stuff, which means that you might serialize everything in memory.

As the lambda expression is an input in to the constructor, in this case it cannot point to `this`. These binding types are all very small classes that are, as it were, small leaves at the end of a structure. So you mention a valid point to realize, but I think we are ok with serializing any part of the tree of generated classes, with binding types as possible leaves.

**Comment by averbraeck** [comment]
See this post about the implicit `this` for a **non-static** field: https://stackoverflow.com/questions/57554966/how-to-serialize-a-runnable-to-execute-code-on-another-infinispan-node (last contribution at the bottom). But since you are serializing `this` [aka `LengthType`] anyhow, this should not be a problem. 

Some good info here: https://blogs.oracle.com/javamagazine/post/behind-the-scenes-how-do-lambda-expressions-really-work-in-java and here: https://www.reddit.com/r/java/comments/10r1762/how_are_lambdas_serialized/

**Comment by averbraeck** [comment]
> I think we are ok with serializing any part of the tree of generated classes, with binding types as possible leaves.

There's only one way to find out, isn't there? :-)

**Comment by WJSchakel** [comment]
Given that both the generated code and binding types are only temporarily used to read/write XML, and that here serialization is only used to directly deserialize it in to a copy, I think we can safely use `SerializableFunction` and make all the binding types `Serializable`.

Only downside I see are the many `serialVersionUID` required.

**Comment by averbraeck** [comment]
For this purpose, it's a nice option that works well as far as I saw in the tests I did. By the way, if you define:

```java
protected static final SerializableFunction<Object, String> TO_TYPE = 
    (o) -> String.valueOf(((Number) o).doubleValue());
```

it does not complain about not having a `serialVersionUID`. So, it's even less work -- you replace `Function` in these classes by `SerializableFunction` and it's done as far as I can see.

**Comment by averbraeck** [comment]
And rolling back is Find-Replace SerializableFunction -> Function in case we do not like it.

**Comment by averbraeck** [comment]
Since these functions are stateless and actually exist for only a few seconds during parsing anyhow (it's not saving a model by serializing and then retrieving it from disk a year later), the `serialVersionUID` does not matter in my opinion.

**Comment by WJSchakel** [comment]
After also making `StripeElement` serializable, I can now run the short merge demo with:

```java
roadLayoutTag = Cloner.clone(roadLayoutTagBase);
```

No specific clone method required. We might bump in to other element not being serializable, which we can fix as required.

**Comment by averbraeck** [comment]
Sounds good! Closing as solved for now?
