### ISSUE TITLE
Repair `ots:Stripe` tag in xml-files of demos

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#176]
The demos that use an `ots:Stripe` tag  such as:

```xml
<ots:Stripe Type="SOLID"/>
```

complain that they are not consistent with the xsd-definition:

```xml
  <xsd:complexType name="CseStripe">
    <xsd:complexContent>
      <xsd:extension base="ots:StripeData">
        <xsd:choice minOccurs="0">
          <xsd:element name="CenterOffset" type="ots:LengthType" />
          <xsd:sequence>
            <xsd:element name="CenterOffsetStart" type="ots:LengthType" />
            <xsd:element name="CenterOffsetEnd" type="ots:LengthType" />
          </xsd:sequence>
        </xsd:choice>
        <xsd:attribute name="Id" type="ots:IdType" use="required" />
        <xsd:attribute name="Type" type="ots:StripeType" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
```

that also has a compulsory `Id` attribute.

**Comment by averbraeck** [comment]
@WJSchakel : When I make the `Id` field in `CseStripe` `optional`, boundaries and stripes are not recognized anymore by the GTUs:

![image](https://github.com/user-attachments/assets/f242a714-6092-4617-952c-7fe220c615be)

**Comment by WJSchakel** [comment]
I'll look into it.

**Comment by averbraeck** [comment]
Note that the `Id` for `CseStripe` is currently `optional` in `definitions.xsd` (line 236) to allow me to compile the project (validation on all xml networks fails otherwise). You can of course turn that back immediately!

**Comment by WJSchakel** [comment]
`public static RoadLayout cloneRoadLayout(final RoadLayout in)` was a method that did **not** copy the `LaneType` in shoulders. Because of this, the following code always took the local `SHOULDER` lane type instance, which allows no GTU types. The mystery of the FIXME is now also solved, it was not copied.

```java
// FIXME: laneType is a mandatory field, but parsing or eclipse is not taking the new field
// although specified in XML, the value is always null
LaneType laneType = shoulderTag.getLaneType() == null ? SHOULDER
        : definitions.get(LaneType.class, shoulderTag.getLaneType().get(eval));
```

Now, with the working general clone method using serialization, the `LaneType` _is_ copied, and this allows GTU types on the shoulder. This is something that we have to fix on the XML side, shoulders do not need a `LaneType` specified, or perhaps in a different manner.

Because TJunctionDemo has no stripes between the normal lane and shoulders, GTU's started to move all over the place.

As to the stripe Id's, I think you didn't have the latest code, as in my XML it has:

```xml
        <ots:Stripe Id="1" Type="DASHED">
          <ots:CenterOffset>1.75m</ots:CenterOffset>
        </ots:Stripe>
```

**Comment by WJSchakel** [comment]
Changed the Id to required on stripes. This is required due to stripe overrides. I get no error about this in XML. I do get the following:

```
Multiple annotations found at this line:
	- cvc-identity-constraint.4.3: Key 'speedlimitGtuTypeRef' with value 'NL.CAR' not found for identity constraint of element 'Ots'.
	- cvc-identity-constraint.4.3: Key 'gtuTemplateTypeRef' with value 'NL.CAR' not found for identity constraint of element 'Ots'.
	- cvc-identity-constraint.4.3: Key 'compatibilityGtuTypeRef' with value 'NL.VEHICLE' not found for identity constraint of element 
	 'Ots'.
	- cvc-identity-constraint.4.3: Key 'shortestRouteMixGtuTypeIdRef' with value 'NL.CAR' not found for identity constraint of 
	 element 'Ots'.
	- cvc-identity-constraint.4.3: Key 'shortestRouteGtuTypeIdRef' with value 'NL.CAR' not found for identity constraint of element 
	 'Ots'.
	- cvc-identity-constraint.4.3: Key 'sinkTypeIdRef' with value 'NL.ROAD_USERS' not found for identity constraint of element 'Ots'.
```

I used to only get this when the XML was opened. It is now permanent since the rename to `ots-xml`. Did we apply a validation skip somewhere in the settings on `ots-parser-xml` that we did not change now?

**Comment by averbraeck** [comment]
Could be. Or we were just lucky that the (re)validation of the xml-files did not take place. Revalidation typically only happens when you change the file itself, or when the project changes so much that a compete rebuild of the tree is done. The project name change for the ots-xml project of course forced all xml network files in ots-demo and other projects to be re-validated...

**Comment by WJSchakel** [comment]
In TurnOnRed.xml and TrafCODDemo2.xml the Ids for stripes were still missing, I did not get errors for this, unless I opened the files. They have Ids now.

**Comment by WJSchakel** [comment]
Now I see more XML's missing the Ids, probably a mixup with my changing them, and you changing the project. Git did not find conflicts as it was in different projects. I'll change them.

**Comment by averbraeck** [comment]
`TurboRoundabout.xml` in ots-demo still needs the stripe changes.

**Comment by WJSchakel** [comment]
> `TurboRoundabout.xml` in ots-demo still needs the stripe changes.

That xml and 3 others, two in the sim0mq projects, now have Id's. The sim0mq xml's were also missing LaneType in Shoulders (although this should change, as mentioned before).

**Comment by WJSchakel** [comment]
Somehow the validation does again only give errors with XML opened. This is fine, and these errors are actually not correct. Id's cannot be found, but they are in the includes that are found.

**Comment by WJSchakel** [comment]
> I have the feeling that the T-Junction demo is behaving very differently from before:
> <image>
> Is that due to recent changes in the XML-definitions, or does it have another cause?

Demo seems familiar to me. The traffic light always caused a lot of spillback.

**Comment by averbraeck** [comment]
Ok! Seems everything is working again after the project rename :-)

I'll continue with adding the ots-opendrive project now (Issue #174). Also a challenge every time...

**Comment by WJSchakel** [comment]
> Ok! Seems everything is working again after the project rename :-)

Mixed in with an ounce of parallel XML changes... ;)
