### ISSUE TITLE
Simplify and finish sampler tables

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#31]
SamplerData is supposed to be able to present itself as a table, so the data can be stored in all sorts of formats. It should also be possible to load this data as a table (not as a SamplerData). There is an initial partial setup for this; it needs to be finished.

Additionally, the class structure can be simplified. The below inheritance structure can probably be simplified to Table, ListTable, SamplerData, Column, and Record.

**Table** < AbstractTable < **ListTable** | **SamplerData**
**Column** < SimpleColumn
**Record** < ListRecord | _Anonymous_

**Comment by averbraeck** [comment]
I like the simplification. A couple of questions:
- What is _Anonymous_?
- I assume the '<' has to be read as 'has as subclass'?
- That probably makes `Table`, `Column` and `Record` interfaces?

**Comment by WJSchakel** [comment]
> * What is _Anonymous_?
There is one anonymous implementation of the Record interface, but that will become a class.

> * I assume the '<' has to be read as 'has as subclass'?
Indeed.

> * That probably makes `Table`, `Column` and `Record` interfaces?
They are now, but there is no need for them to be an interface. The functionality of the implementing classes will be placed under those names.

**Comment by WJSchakel** [comment]
The table functionality has been completed.
- `Column` received an additional field; unit.
- `SamplerData` can return an `Iterator<Row>` which internally loops over lanes, trajectories on each lane, and the index over each trajectory.
- `TableCsvWriter` has been created. It uses a format String, locale, value separator, and a set of optional `TableCsvWriter.Marshaller`s to transform a value in to String. Next to the csv file, the writer also saves a **header file** under the same name, with '.header' appended. Per column it writes three lines for: id, description, value type class. An optional 4th line may contain the unit. The writer replaces a method in `SamplerData`, and is also faster.
- `TableCsvReader` has been created. It uses a locale, value separator, line terminator, and a set of optional `TableCsvReader.Unmarshaller`s to transform String in to a value. It creates `Column`s for the table from the header file. For each line it adds a `Row` to a `ListTable`. Columns in the header file and the table file must match, though their order in each file is not important.

**Comment by WJSchakel** [comment]
A number of classes is eligible to be grouped somewhere else; they are not intrinsic to sampling: `Table`, `ListTable`, `Column`, `Row`, `TableCsvWriter` and `TableCsvReader`.

**Comment by WJSchakel** [comment]
`TableCsvReader` no longer has a `setLocale()` and `setSeparator()` method. This information is now written in to the header file by `TableCsvWriter`. The method `setDelimiter()` is still present in `TableCsvReader`, as this is required to delimit the lines while reading the header file (i.e. we thus can't store that information in the header file).
