### ISSUE TITLE
Merge ots-kpi and djutils-data table functionality 

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#33]
Development of tables to work with various writers/readers has had a parallel history in ots-kpi and djutils-data, but clearly from the same root. This functionality is still very similar and can be merged in to one consistent functional package.

**Comment by WJSchakel** [comment]
It was fairly easy to copy the code of djutils-data in to ots-kpi, to get rid of all the errors (mostly by renaming a bunch), and to get `SamplerData` to work with the writers and readers for csv, json and xml of djutils-data. The packages were still highly similar. The following changes have been made to the code from djutils-data:
- `Column` has a unit field, which may be `null`.
- `StringSerializer` did not deal with `null`. To serialize it now does: `return value == null ? null : value.toString();`.
- XML lines such as `<value nr="0" content="1"></value>` are now written in their shorter form `<value nr="0" content="1"/>`.  This also holds for the `<column ... />` tag.
- `JsonData.readValue(...)` now check whether the value is `null` using `jr.peek().equals(JsonToken.NULL)`.
- In many of the writers there were unnecessary `finalize` blocks where `try-with-resources` blocks were appropriate. The latter has been implemented.

Some issues remain:
- When writing a `org.opentrafficsim.kpi.sampling.SamplerData`, the readers complain it is not a `org.opentrafficsim.kpi.sampling.ListTable`. For now, the read field is overwritten in the code with `org.opentrafficsim.kpi.sampling.ListTable` such that this table type is loaded.
- All writers write the data as `"org.djunits.value.vfloat.scalar.FloatDuration#3.0 s"`, while both the data type and the unit are known in the column. This example could simply be `"3.0"`.

**Comment by averbraeck** [comment]
This looks good to me. The `TableData` in the new form with units has a lot of added value. Combining it with fastcsv's CSV reader and writer that will make sure the CSV files are 100% consistent with CSV standards, and the xml-, json- and binary readers/writers will create a nice package that can be moved back to djutils-data when it is ready. I agree with how the open issues are handled.

**Comment by WJSchakel** [comment]
The `PrimitiveSerializer` (and all its static instances for different primitive types) has been removed. Due to auto(un)boxing, there was literally no difference between e.g. `PrimitiveSerilizer.Int` and `IntegerSerializer`.

`FloatScalarSerializer` (for DJUNITS types) extends `DoubleScalarSerializer`, but only overrides `serialize(S value)` using `value.floatValue()`. They used to be two practically identical classes.

In the future we can support reading more table types, rather than only `ListTable`. As a `Table` is read-only, any class implementing `Consumer<Object[]>` can be used by the reading algorithm to write data in to the table. This could even be achieved with an ad-hoc wrapper, as is the case for how `ListTable` is filled with data.

```
Table table;
Consumer<Object[]> unserializableTable;
if (tableRow.get("className").equals(ListTable.class.getName()))
{
    ListTable listTable = new ListTable(tableRow.get("id"), tableRow.get("description"), columns);
    table = listTable;
    unserializableTable = (data) -> listTable.addRow(data);
}
...
unserializableTable.accept(values);
```

`CsvData` now support writing both the CSV file and the header file in to a single ZIP file. For this, it uses a new version of `CompressedFileWriter`. This class is now a `AutoClosable` resource with a `next(String)` method to write in to the next file inside the ZIP file.

**Comment by WJSchakel** [comment]
I think the code is now ready to be moved from ots-kpi to DJUTILS. This involves:
-`Table`
-`Row`
-`Column`
-`ListTable`
-`CompressedFileWriter` (now in `org.opentrafficsim.base`)
-`org.opentrafficsim.kpi.sampling.serialization` package
-`org.opentrafficsim.kpi.sampling.csv` package
-`org.opentrafficsim.kpi.sampling.json` package
-`org.opentrafficsim.kpi.sampling.xml` package

I suggest merging the contents of the latter 3 packages in to 1 package. It is 4 classes total that do very similar things.

Once the code has been moved, the following dependencies can be removed from ots-kpi:
-de.siegmar (fastcsv)
-com.google.code.gson

**Comment by averbraeck** [comment]
I will make an issue in djutils to move the code over to djutils. This will be in version 2.1.7 (I just pushed v2.1.6 for the `testFail` and `testSucceed` methods in djutils. As soon as I moved the code, and the unit tests are working, I will change the pom file in ots and close this issue.

**Comment by averbraeck** [comment]
@WJSchakel : The method `deserialize()` in the `CharacterSerializer` looks very strange to me. Probably a (mis)copy from `DoubleScalarSerializer`? And there might be a more elegant way to get the proper string in `serialize()`.
