### ISSUE TITLE
What to do with the compressedfiles package in ots-base?

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#36]
In addition to the `CompressedFileWriter` class (that will move to djutils-base), there is a compressedfiles package in ots-base with a `Reader` and `Writer` class, and a `CompressionType`. These are unrelated to `CompressedFileWriter`, and the `Reader` and `Writer` are not used in OTS as far as I can see. My suggestion would be to remove the package at the moment, and consider moving it to djutils, but I am hesitant to do so, since there is no use of these classes right now, and it is just a maintenance burden.

**Comment by WJSchakel** [comment]
I think it can be removed. `CompressedFileWriter` is a sufficient tool, we do not need various types of compression. We might extend it with a method that can deliver a set of `InputStream`s to read files inside a zip file. A generalized version of what now occurs in `CsvData.readZippedData`. I think there would be two ways to use that:
- Know the file names: `InputStream[] getInputStreams(String zipFileName, String... fileNames)`
- Do not know the file names: `Map<String, InputStream> getInputStreams(String zipFileName)` (where the map keys are file names)
We can do this now, or later.

**Comment by WJSchakel** [comment]
We may also wrap those `InputStream`s in a `InputStreamReader`, and wrap that in a `BufferedReader`. Not sure about this, there is a clear balance between convenience and flexibility.

**Comment by WJSchakel** [comment]
Another idea, rather than knowing the file name of files in the zip file, we could also pattern match. E.g.:
`InputStream[] myStreams = getInputStreams("myZipFile.zip", "*.csv", "*.csv.header");`
