### ISSUE TITLE
Self-referring links in manual are broken

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#37]
Due to the move of manual structure, the links that refer to parts of the manual itself are broken.

**Comment by WJSchakel** [comment]
@averbraeck How do we make consistent relative URL's? The link `/manual/02-model-structure/events/` works for opentrafficsim.org, but not for readthedocs.io. There, this results in `https://opentrafficsim.readthedocs.io/manual/02-model-structure/events/` but should be `https://opentrafficsim.readthedocs.io/en/latest/02-model-structure/events/`.

**Comment by averbraeck** [comment]
What move of the manual took place? Because right now, it really has to reside as a 'docs' folder in the project root of the parent project to work (all scripts on the Delft server are also rely on that).

**Comment by WJSchakel** [comment]
It was a while ago when you placed it in the current automated workflow using the .yml file. At least, I assume that's when the links got broken. For example we have `[Deviative nature of operational plans](/behavioral-models/tactical-planner#operational-plan)`, which has the old folder structure in it. It should in the end refer to `https://opentrafficsim.org/manual/06-behavior/tactical-planner/#operational-plan`.

**Comment by averbraeck** [comment]
The events page that you used as an example works fine, both on readthedocs and on opentrafficsim.org. Of course, I had to refresh the page (ctrl/f5 in the browser) to reload the structure. Or do you mean the links within a certain page to another page?

The only ting that did not work for me were the links on the tutorial page.

**Comment by averbraeck** [comment]
And the tutorial page now also works.

**Comment by WJSchakel** [comment]
On the djutils page (https://opentrafficsim.readthedocs.io/en/latest/02-model-structure/djutils/) on readthedocs, when I click on the event list link, I'm referred to: 

https://opentrafficsim.readthedocs.io/manual/02-model-structure/events/ 

This is a page, but it has no layout and only shows the menu in the most basic html formatting. It should refer to:

https://opentrafficsim.readthedocs.io/en/latest/02-model-structure/events/

The perception is broken too. I see the same ugly menu. It should also refer to .../perception/**introduction/** as the chapters no longer have an introduction that is not a sub section.

**Comment by averbraeck** [comment]
So it is about (relative) links on pages. I will check.

**Comment by averbraeck** [comment]
Links now work, in opentrafficsim.org, in readthedocs, and also in Github itself. Note that:
- references should ALWAYS be relative (so using ../
- for links to also work in Github, add the '.md' to the filename. The compiler will replace this with .html for readthedocs and opentrafficsim.org.
- a file that is on the same level, does not need a subdirectory, so the link to the 'event' page was just: `\[[List of all event types in OTS](events.md)\]`. 
- you can use anchors as you would do normal; so for 08-tutorials/index.html: `[How to set up a simulation](simulation-setup.md#how-to-set-up-a-simulation)<br>`. Again, the filename has the .md to make it work in Github as well.

**Comment by WJSchakel** [comment]
All links have been fixed. The trick is really to always point to a .md, even when referring to a section as a whole.
