### ISSUE TITLE
Zoom scale messed up at start-up or dragging

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#41]
When a simulation is started with visualization, the default screen size seems to be very small in height. The default zoom scale is based on this screen size, before the window is maximized. This leaves the network tiny on the window.

When dragging the window, it falls back to the previous size. To fit the expanse visible at full screen, the zoom scale gets even worse. This also happens when you drag to another monitor, and drag it (all in one go) to the top of the other monitor to maximize there again. 

The default screen size should be larger. And ideally the zoom scale should not change during dragging from a full screen. At release of the drag, the scale may be updated. (This is of course not an issue during normal dragging, as the screen size is then not changed.)

**Comment by averbraeck** [comment]
I have noticed this issue. It resides in dsol, where it should be solved. The internal dsol animations have exactly the same problem.
