### ISSUE TITLE
Streamline object.trafficlight and ots-trafficcontrol

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/opentrafficsim#53]
[**ots-road**] In the package `org.opentrafficsim.road.network.lane.object.trafficlight` we have:
- `class SimpleTrafficLight` extends `abstract class AbstractTrafficLight` implements `interface TrafficLight`

- `abstract class AbstractTrafficLightController` implements `interface TrafficLightController`
- `class TrafficLightControllerFixedDuration` implements `interface TrafficLightController`
- `enum TrafficLightColor`
- `class TrafficLightException`
<br>

[**ots-trafficcontrol**] In the package `org.opentrafficsim.trafficcontrol` we have:
- `class FixedTimeController` extends `abstract class AbstractTrafficController` implements `interface TrafficControl`.

- `class TrafCod` extends `abstract class AbstractTrafficController` implements `interface TrafficControl`.
- `class Ccol` implements `interface ActuatedTrafficController` extends `interface TrafficController`.
- `class Diagram` (draws standard Dutch stream schemes)
- `class TrafCodDisplay` (visualizes TrafCod state)
<br>

**Issues**:
- Why do we have a separate ots-trafficcontrol project?

- Class `AbstractTrafficLightController` has no concrete implementations.
- Classes `TrafficLightController` and `TrafficController` are semantically too similar. It seems that `TrafficLightController` has no real purpose. It is an `Identifiable` with some _getters_ and an _add_ that seem specific to the implementation (of which we only have `TrafficLightControllerFixedDuration`). `TrafficController` only seems to group functionality (interfaces, static fields). Is there a good argument for these interfaces? (There is also no common animation, and for specific animation, being a `(Non)LocatedObject` is sufficient.)
- Classes `TrafficLightControllerFixedDuration` and `FixedTimeController` are semantically too similar. The former works with _phases_, and the latter with `SignalGroup`s. Is there an arguable difference in resulting functionality or usage?
- Animation is intertwined with functionality. For example we have `ActuatedTrafficController.getDisplayContainer()` and `TrafCodDisplay`. This should move to ots-draw.
- All these controller are fairly complex. What if we just want a single traffic light with fixed time phases? See `TJunctionModel.changePhase(...)`.
- Class `TrafCodDisplay.TrafficLightImage` implements `TrafficLight` solely for the `setTrafficLightColor()` method. It can have a separate method without the dependency.
- It seems this class structure could be consolidated in about half as much, clearer, classes.

**Comment by averbraeck** [comment]
> Why do we have a separate ots-trafficcontrol project?
I don't think this is necessary anymore. My suggestion would be to integrate it into the ots-road project. Also because it has many (potential) relations with perception classes.

> Class `AbstractTrafficLightController` has no concrete implementations.
Let's get rid of it. I think the `TrafficLightController` interface, potentially with a few `default` methods, is sufficient.

> Classes `TrafficLightController` and `TrafficController` are semantically too similar.
Agree. A `TrafficController` sounds much broader, though, than a `TrafficLightController`, and might have nothing to do with lights.

> Classes `TrafficLightControllerFixedDuration` and `FixedTimeController` are semantically too similar. 
Agree. Rationalizing this and creating a simple traffic light situation with phases, and set green times, yellow times and red times should be much easier than it is now. This should work without any detectors (answers the one-but-last bullet as well).

> When we move the classes to ots-road, separating the animation into ots-draw will be much easier. Earlier, ots-draw was not dependent on ots-trafficlight, and therefore ots-trafficlight had to implement its own animation...

> It seems this class structure could be consolidated in about half as much, clearer, classes.
Indeed. And let's move these classes to ots-road, since it has to do with roads. Earlier we though to also use these classes for rail signaling, traffic lights at bridges and locks for boats, etc. Since we never implemented those, let's reverse it. For now, we only have good traffic light functions for roads. Then let's implement that properly, and worry about expansion and separation into a separate project when that's appropriate. We also want the traffic lights to be parsed from XML files by the xml-parser project. Integration into ots-road also helps with that.

**Comment by averbraeck** [comment]
Also, what is `SimpleTrafficLight`? Is there also a `ComplexTrafficLight`? I think with Simple we mean a 3-color traffic light. Again, there are multiple implementations even of a 3-color traffic light. In Austria and some other countries, green+orange announce the green phase, just like orange announces the red phase. In NL, we do not have this. So even a 3-color traffic light can have multiple implementations. Naming should be more clear than what we have right now! Probably there is some standard naming that we can relate to with the class names and method names?

**Comment by averbraeck** [comment]
> class `Diagram` (draws standard Dutch stream schemes)

That name is too generic; It should be `SomethingDiagram` where 'Something' should clearly point out what we can expect in the diagram...

**Comment by WJSchakel** [comment]
The package in road is now consolidated.
- Removed interface `TrafficLight` and `AbstractTrafficLight`. Contents moved to `SimpleTrafficLight`.
- Renamed `SimpleTrafficLight` to `TrafficLight`.
- `TrafficLightImage` from `TrafCodDisplay` no longer implements `TrafficLight`. This breaks the connection with the animation that was directly informed by TrafCod. This will need to be replaced by pub/sub in dedicated animation.
- Removed interface `TrafficLightController`, `AbstractTrafficLightController` and `TrafficLightControllerFixedDuration`. For the latter, `FixedTimeController` from ots-trafficcontrol is a suitable replacement. `TrafficLightController.SignalGroup` is a good candidate for a simple controller for a single traffic light.
- Removed `TrafficLightException`, `TrafficControlException` from ots-trafficcontrol is a suitable replacement.

The package now only contains: `TrafficLight` and `TrafficLightColor`. Classes from ots-trafficcontrol can be moved to it, minus the animation.

**Comment by WJSchakel** [comment]
> Also, what is `SimpleTrafficLight`? Is there also a `ComplexTrafficLight`? I think with Simple we mean a 3-color traffic light. Again, there are multiple implementations even of a 3-color traffic light. In Austria and some other countries, green+orange/yellow announce the green phase, just like orange/yellow announces the red phase. In NL, we do not have this. So even a 3-color traffic light can have multiple implementations. Naming should be more clear than what we have right now! Probably there is some standard naming that we can relate to with the class names and method names?

There is now just `TrafficLight`, which can display any `TrafficLightColor` it wants. There are now 5 colors: RED, YELLOW, GREEN, PREGREEN and BLACK. PREGREEN is (I think) what announces GREEN. Functionally this is quite elegant, we do not care how exactly a traffic light announces this. There are also counters, for example.

**Comment by WJSchakel** [comment]
The constructor of `FixedTimeController` does some work on `SignalGroup`s. The result is still a set of those. The underlying merging of the groups should become an external procedure; it is not inherent to the `FixedTimeController`.

**Comment by WJSchakel** [comment]
The constructor of `FixedTimeControl` was too long. A big chunk of it involved taking out traffic lights that are present in multiple signal groups, and creating their own group with green whenever one of the original groups allowed. This has been moved to a separate method. Added some more documentation throughout the class.
