### ISSUE TITLE
Simplify and streamline Compatibility

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#6]
The code has Compatibility and Compatible interfaces. It is not clear what the difference is, since they both have the isCompatible(..) method. Also, constructors of infrastructure immediately need a Compatibility structure, whereas it is sometimes not possible to provide that before other model elements have been defined. So it would be much better to define infrastructure without compatibility features fist, and add compatibility AFTER the infrastructure has been created.

Furthermore, the implementation of the GTUCompatibility class, that defines compatibility between infrastructure and the GTU as a user of that infrastructure, can be further streamlined. The order in which a GTU hierarchy with allowed and disallowed usage of parts of an Infrastructure hierarchy is evaluated, can lead to ambiguous outcomes. The order in which compatibility is examined should be defined in a much more strict way.

**Comment by averbraeck** [comment]
In order to make dynamic compatibility changes possible, HierarchicalType has been extended with a set of existing children. This Set can be used when compatibility needs to be recalculated. Any change to the compatibility of a type can have effect deeper in the hierarchy of types, and as a result, the children need to be able to clear their cache so the cache can be recalculated. The list of children helps to accomplish that.

**Comment by averbraeck** [comment]
Implemented in branch feature-compatibility which has been merged into main.

**Comment by WJSchakel** [comment]
OtsNetworkTest and OtsLinkTest create errors due to compatabilities being generated with a null LinkType. Was this induced by this issue?
