### ISSUE TITLE
Questions regarding what OTS can do

### ISSUE THREAD

**Issue by JulienCros** [averbraeck/opentrafficsim#61]
Hello,

We are a small company that creates historical experiences where groups will follow a "scenario" through different stages to explore both through time and space a historical building/epoch.
We use big rooms where groups are sent into the experience every few minutes.

The scenario is divided in "steps" where the "players" will remain for a bit in a designated area of which the size varies depending on the script.

Our objective is to optimize the path to avoid as much as possible encounters between different groups. Which means it is important to be able to simulate how the players wander around in each step to take a look around while remaining in the scene.

 
Do you think it is feasible, using your library, to create scenarios with a succession of goals and agents (pedestrians) wandering around in a defined area for a specified time at every goal ? 
For example by creating many small targets and making the agents randomly chose one and wait randomly until the step's time has ended ?

I've tried following your guides but even when I copy the code from ots-demo, I still get many errors as shown below.

![image](https://user-images.githubusercontent.com/44341623/222160763-b96772ed-03fb-4148-8a85-c8b577fcd204.png)

And yet I have added every dependency possible in the pom.xml file !

![image](https://user-images.githubusercontent.com/44341623/222161432-1fb4c6e4-2024-46f4-8a10-c556c7c1a9fe.png)
![image](https://user-images.githubusercontent.com/44341623/222161579-92748c4e-85f0-4d20-9e04-717e20155f9c.png)

Best Regards,
Julien CROS
https://immersive-expeditions.io/

**Comment by JulienCros** [comment]
After further investigation it seems I have somehow downloaded an old version and I guess the tutorial is no longer up-to-date and you also removed it from the ots-demo folder.

**Comment by WJSchakel** [comment]
Hello,

Our documentation is available on https://opentrafficsim.org/manual/. It is quite up to date. OTS is about road traffic, so it does not look particularly suitable for your use case.
