### ISSUE TITLE
Restructuring of animation code

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#64]
Following on https://github.com/averbraeck/dsol/issues/7 and to help address issue #63, the project structure for animation in ots can be improved. To solve issue #63, independent data objects (or interfaces) need to be created between the animation and the source of the animation. These independent data objects can link all functions to request information on the network and gtu objects to the 'real' objects in ots-core and ots-road for the animation of an ots simulation model, and to a number of properties or constants in case the animation objects that have to be drawn belong to the XML-information in the editor. 

In order to not make the ots-editor project dependent on ots-core, ots-road, and ots-trafficcontrol, these data objects and the paint methods for these data objects need to reside in a project that is different from the project that uses information from ots-core, ots-road, and ots-trafficcontrol. Therefore, the suggestion is to split the visualization information over two projects in a bit different way than it is done right now.

**ots-draw** will be dependent on dsol-draw, and **not** on ots-core, ots-road, and ots-trafficcontrol, and contains the data objects for drawing, the paint methods for drawing the objects, and associated styling objects if needed.

**ots-animation** will be dependent on ots-draw, ots-core, ots-road, and ots-trafficcontrol and contains the implementation of the data objects that retrieve their information from the real infrastructure and gtu objects. 

**ots-editor** will be dependent on ots-draw, and on dsol-animation and **not** on ots-core, ots-road, and ots-trafficcontrol, and contains the implementation of the data objects that retrieve their information from the XML data. The dependency on dsol-animation is for access to the `VisualizationPanel` that enables `Locatable` objects to be drawn based on the `Renderable2D` interface from dsol-draw.

**ots-swing** will be dependent on ots-animation, on dsol-animation and dsol-swing, and on ots-core, ots-road, and ots-trafficcontrol, and contains the full user interface code for OTS using swing.

**ots-web** will be dependent on ots-animation, on dsol-animation and dsol-web, and on ots-core, ots-road, and ots-trafficcontrol, and contains the full user interface code for OTS using HTML-5.

Note that the ots-core, ots-road, and ots-trafficcontrol projects are (and will remain) completely unaware that animation even exists. These projects will fire events when objects are added or removed from the simulation, and will make properties that could be important for drawing available through a public getter.

**Comment by averbraeck** [comment]
As an example, the design line of a `Link` will be displayed as follows for the **swing animation**:
- ots-draw contains a `LinkData` interface or abstract object with, e.g., a `getDesignLine()` method. The `LinkData` object implements `Renderable2D` and contains a `paint()` method to draw, a.o., the design line.
- ots-animation contains a `LinkData` implementation with an implementation of the `getDesignLine()` method. This method is implemented by retrieving `link.getDesignLine()` to obtain the real design line of the network object in the simulation.
- ots-animation populates all these data objects at the start of the simulation by calling the `DefaultAnimationFactory` to make all the data objects and to subscribe to network change events. 
- ots-swing or ots-web visualize these data objects that have a `paint()` method (implemented in ots-draw) in an animation tab that contains the `AnimationPanel` from dsol-swing.

The design line of a `Link` will be displayed as follows for the **ots editor**:
- ots-draw contains a `LinkData` interface or abstract object with, e.g., a `getDesignLine()` method. The `LinkData` object implements `Renderable2D` and contains a `paint()` method to draw, a.o., the design line.
- ots-editor contains a `LinkData` implementation with an implementation of the `getDesignLine()` method. This method is implemented by retrieving XML data for the link to obtain the defined design line of the link in the editor.
- ots-editor visualizes these data objects that have a `paint()` method (implemented in ots-draw) in panel that contains the `VisualizationPanel` from dsol-animation.

**Comment by averbraeck** [comment]
As an example, the color of a `LaneBasedGtu` will be displayed via a `Colorer` for the **swing animation** as follows:
- ots-draw contains a `GtuData` interface or abstract class with, e.g., a `getColor()` method. The `GtuData` object implements `Renderable2D` and contains a `paint()` method to draw, a.o., the color of the `LaneBasedGtu`.
- ots-animation contains an `AnimationGtuData` class with an implementation of the `getColor()` method. This method is implemented by delegating the retrieval of the color to a `GtuColorer` to obtain the current color of the `LaneBasedGtu`object in the simulation.
- ots-animation has the implementation for the used `GtuColorer` that returns a color based on properties of the `LaneBasedGtu` that is defined in ots-road. 
- ots-animation populates all the data objects at the start of the simulation by calling the `DefaultAnimationFactory` to make all the data objects and to subscribe to network change events. 
- ots-swing or ots-web visualize these data objects that have a `paint()` method (implemented in ots-draw) in an animation tab that contains the `AnimationPanel` from dsol-swing.

The template of a `Gtu` will be displayed as follows for the **ots editor**:
- ots-draw contains a `GtuData` interface or abstract class with, e.g., a `getColor()` method. The `GtuData` object implements `Renderable2D` and contains a `paint()` method to draw, a.o., the color of the `Gtu`.
- ots-editor contains an `EditorGtuData` class with an implementation of the `getColor()` method. This method always returns, for instance, `Color.BLACK`.
- ots-editor visualizes these data objects that have a `paint()` method (implemented in ots-draw) in panel that contains the `VisualizationPanel` from dsol-animation.

**Comment by WJSchakel** [comment]
To achieve the goals of this issue, the following dependencies in `ots-draw` need to be addressed.
1. The `AbstractPlot` class and all sub classes (which are all plots) requires an `OtsSimulatorInterface` for plot updates as simulation progresses.
- We could instead use `DevsSimulatorInterface<Duration>` from `dsol-core`.
- We could define an interface `PlotScheduler` that wraps an `OtsSimulatorInterface` during simulation, but could wrap some other object for offline use.
- Move graphs to `ots-animation`.
2. Graphs depend on `ots-kpi` as the graphs are based on the `Sampler` and the classes it contains.
- Make `ots-draw` dependent on `ots-kpi`.
- Move graphs to `ots-animation`.
3. `ContourPlotDelay` depends on `ReferenceSpeed` from `ots-road`, which is an `ExtendedDataSpeed<GtuDataRoad>` as used in the `Sampler`.
- Add a reference speed to `GtuData` in `ots-kpi`, implement `ReferenceSpeed` as `ExtendedDataSpeed<GtuData>` and move it to `ots-kpi`.
- Define `GtuDataReference` in `ots-kpi` as an extension of `GtuData`, implement `ReferenceSpeed` as `ExtendedDataSpeed<GtuDataReference>` and move it to `ots-kpi`.
4. `TrajectoryPlot` depends on `IdGtuColorer` from `ots-animation`.
- Define the id-color logic in a static place in `ots-draw`, and use it in `TrajectoryPlot` and `IdGtuColorer`.
- Move graphs to `ots-animation`.
5 `FundamentalDiagram` uses `RoadSampler` and `LaneDataRoad` from `ots-road`.
- This has already been generalized to `Sampler` and `LaneData`. Hence `ots-draw` should depend on `ots-kpi`.
6. `GraphLaneUtil` uses `CrossSectionLink`, `Lane`, `LanePosition` and `LaneDataRoad` from `ots-road`.
- Move `GraphLaneUtil` to `ots-road` (`org.opentrafficsim.road.network.sampling`).
7. `PaintLine` depends on `OtsGeometryException` and `OtsLine2d`.
- It has already been generalized to use `PolyLine2d` which throws no exception.
8. `LaneStructureAnimation` and `LaneStructureLocatable` depend on `ots-road`. These will be removed in the future.
- Move to `ots-animation` until they are removed.

Several issues (1, 2, 4) are solved if we move the graphs to `ots-animation`. However, `ots-animation` is live, whereas `ots-draw` is generic and also offline. Graphs also have an offline character. Ideally it would be possible to create graphs from data, where the data is an _instant simulation until the simulation end time_. As such we need wrapper classes, i.e. `PlotScheduler` for issue **1**.

Two issues (**2**, **5**) are solved by making `ots-draw` dependent on `ots-kpi`, which seems a logical thing to do.

Issue **3** is proposed to be solved by adding `getReferenceSpeed()` to `GtuData`.

Issue **4** is proposed by defining a static list of 10 colors in `ots-draw` to be used by `IdGtuColorer`.

Issue **6**, **7** and **8** have one mentioned solution, which will thus be chosen.

**Comment by WJSchakel** [comment]
All the above is done. Furthermore the EGTF code is move to `ots-draw`. We could consider moving this to a more generic location, as this method is not at all drawing specific. Perhaps `ots-base`. Note that `ots-draw` is currently not dependent on `ots-base`.

With the code moving around between projects, many package names have been changed inside `ots-animation` and `ots-draw`. Similar package name chaos still exists in other projects.

**Comment by WJSchakel** [comment]
A first dummy lane is now drawn when running the editor.
