### ISSUE TITLE
Make Sensors a full infrastructure element

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#7]
Right now, sensors are part of the infrastructure, but unlike links and lanes, they do not implement a SensorType that shows a hierarchy, compatibility, and common properties. Instead, compatibility of sensors is implemented on the instance level leading to data duplication and repeated caching of properties that should theoretically only be evaluated once. 

Introducing a SensorType and making the SensorType a HierarchicalType with GTUCompatibility will solve a lot of inconsistencies in the library.

**Comment by WJSchakel** [comment]
Merged with issue #12
