### ISSUE TITLE
Handle DEFAULTS in another way

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#8]
LinkType, LaneType and GTUType have a DEFAULTS section that defines a few "defaults". This has a couple of disadvantages:

1. It is not clear without looking at the code how these have been defined and what compatibility they have;
2. Parsing is more complicated because it has to 'combine' existing types and user defined types;, where the existing types can not easily be referenced within the XML file because they are not defined in XML.
3. Sometimes when infrastructure is truly different for a test, (some of) the 'default' types have to be removed.

Therefore it is proposed to remove the DEFAULTS from the classes themselves. Of course, a utility class can define one or more sets of defaults for different purposes. For the parser, one or more XML include files can define useful sets of defaults as well.

**Comment by WJSchakel** [comment]
We agree to make separate issues to remove the use of DEFAULTS in specific contexts. Here we specify which packages/classes will be handled in the issue.

**Comment by averbraeck** [comment]
@WJSchakel : Please take a look how I solved the issue for the NodeType class. For now, I think this is the best option for the LinkType, LaneType, GtuType and DetectorType classes as well. It combines total freedom for how you want to implement a hierarchy for a particular network, while still having a vocabulary of "useful" types such as a car. truck and bus that have been defined. As long as the names match, the generic types with a null network are equal to (equals() returns true) named types in a network that use the same name. We have to see if the parent also needs to match, or whether the network can define a different hierarchy. I tend to favor the 'id only' option here.

**Comment by WJSchakel** [comment]
We have to consider the relation between types and their network. The main reason this connection was made, is such that types could be obtained from the network, e.g. OtsNetwork.getGtuType(final String gtuId), or using the current DEFAULTS. I think those methods will no longer be useful as either:
1. you have to use a specific custom type, or
2. you use a type in a static field directly.
For point 1 you could use the network as a storage space, but that is pointless as you would still need to give the String name as an argument to whatever place needs the GTU type. You could just as well give the GTU type itself. So it seems to me that the whole connection with the network can be dropped.

**Comment by WJSchakel** [comment]
Another question is whether the static default types could be used in certain places/algorithms. For example a detector simply using GtuType.VEHICLE. I get that a custom CAR type, with as parent a custom type also with id VEHICLE, will trigger the detector, due to the suggested simplified equals() method. But, this does force any GTU type hierarchy to use that String id in order for the GTU's to trigger detectors. I think it would be good practice not to do this, and always provide types as arguments. The static default types then only have one purpose: to be used upon setting up a simulation, without having to setup your own GTU type hierarchy necessarily.

**Comment by averbraeck** [comment]
After discussion, we decided the following:
- Get rid of ALL the DEFAULTS. The current implementation just creates issues.
- Remove the LinkType, LaneType, GtuType, DetectorType, NodeType from the Network. Why would we need to search the types by String? 
- Make utility classes that can generate a set of default types for, e.g., The Netherlands, or for a theoretical situation.
- Make sure we can use that standard from XML, where both XML and regular coding can create any hierarchy of types and related compatibilities that we need.
- Where classes or methods are dependent on a type, provide the types in the constructor or the method call. An example is the GtuTypeColorer that would simply get a Map of GtuType to Color for its constructor. Much more flexible and it avoids the dependency on some random set of 'defaults'.

**Comment by WJSchakel** [comment]
Rather than utility classes, define the default types in xml files. Parsing can be done using e.g. org.opentrafficsim.road.network.factory.xml.parser.parseGtuTypes(DEFINITIONS), where DEFINITIONS can be derived from the xml file in a separate static method.

**Comment by WJSchakel** [comment]
> Rather than utility classes, define the default types in xml files. Parsing can be done using e.g. org.opentrafficsim.road.network.factory.xml.parser.parseGtuTypes(DEFINITIONS), where DEFINITIONS can be derived from the xml file in a separate static method.

On second thought, this will not work. The parsed GTU types need to be accessed in some way, e.g. using a Map<String, GtuType> from which the types are retrieved as map.get("VEHICLE"). Now, if the standard types are changed, no errors will occur at compile time. But at runtime the GTU types may not be found for many simulations. So, it would be better to define standard types in a java class, to which xml may refer. Xml may still use custom types, and existing code is changed in compile time if the standard is changed.

**Comment by WJSchakel** [comment]
`GtuType.DEFAULTS` has been removed, this has meant a plethora of changes.

1. Classes `Defaults` and `DefaultsNl` added in the definitions package. Defaults for other locales may be added. Defaults regarding other types (LaneType, LinkType, etc.) may also be included here. The class `Defaults` is the central place to find defaults. Other classes such as `DefaultsNl`, implement/contain the functionality for a locale.
2. `GtuType` is no longer dependent on a network. This is very convenient in many places, but does require explicit registration in the network (`OtsNetwork.addGtuType()`) if a simulation requires it. The XML parser does this automatically. Only RampMeteringDemo required explicit registration.
3. The LaneBiases for OD-based GTU generation are now by default empty (i.e. uniform distribution). The default was TRUCK_RIGHT for trucks, and WEAK_LEFT for other traffic (type vehicle). This must now be set for each simulation that uses an OD. The XML parser does this if no biases are defined. RampMeteringDemo is the only simulation that requires explicit setting of WEAK_LEFT (it has no trucks).
4. `Lane` has fewer constructors now. As a GTU type for speed limits was required as input anyway (we can no longer use a default inside the constructor), just use `Map.of(GtuType, Speed)` to directly provide a speed-limit map.
5. There are several places where general/parent GTU types are required, for which nothing can be done from the XML parser. For now, `DefaultNl` types are used. These places are:
- `DefaultAnimationFactory.animateNetwork()`; _square type_, what GTU type (and its sub-types) to draw as a square when zoomed out. However, it is probably better to define this at the GTU type level (with a circle as default). This may be similarly implemented as GTU type colors in `GtuType`. _An issue will be made for this._
- `DefaultAnimationFactory.animateNetwork()`; _permeability type_, what GTU type to use to check stripe permeability, and hence what to draw (dashed/continuous). However, this must be changed as the resulting `StripeAnimation.TYPE` should probably become a property of the `Stripe` directly. _An issue will be made for this._
- `ConflictBuilder` uses a GTU type to allow conflicts to find next/prev lanes, on which to find GTUs. This seems not required, as `Lane` allows a `null` GTU type to find _all_ upstream or downstream lanes. _An issue will be made for this._
- `LaneBasedGtuGenerator.getFirstLeaders()` uses a GTU type to find next lanes, on which to find downstream vehicles that may not allow sufficient space for vehicle generation. Similar to the point above, we could just use `null`. _An issue will be made for this._
- `Lane.noTrafficLane()`, only used by the XML parser, requires a GTU type to create a speed-limit map with zero speed. We can fix this by overriding the `getSpeedLimit()` method in the anonymous class that was already used, and just return `Speed.ZERO` for any GTU type. No GTU type is required, and an empty map is used instead.
- `StrategicalPlannerFactorySupplierOd.lmrs()` uses a truck type to set different parameter values _if DefaultsNl.TRUCK is used_. If a user uses other GTU types without specifying parameters, they will drive as cars.

Considering point 3 above; what if a user defines a non-default GTU type "ROAD_USER", but wants no lane bias? Now, the XML parser _magically_ applies a lane bias as the GTU types will match. To prevent name clashes it would generally be better to name all default NL GTU types as NL.CAR, NL.TRUCK, etc. Right now this is not yet done for consistency with the XML defaults specification. Note that not only the name, but also the parent structure needs to be the same to have a true clash. We could facilitate a _default_lane_biases.xml_ file that may be included:

- TRUCK: FROMLEFT=0.0, BIAS=5.0, STICKY_LANES=2
- ROAD_USER: FROMRIGHT=0.0, BIAS=2.0

**Comment by WJSchakel** [comment]
`GtuType`, `LinkType`, and according to issue #14 `NodeType` [too](https://github.com/averbraeck/opentrafficsim/issues/14#issuecomment-1281698098_), are or should be added to a `OtsNetwork`. But I think this should not be done as this again creates a String-id-based or DEFAULTS-based contract between `add` and `get`. The network is now mostly used by the xml parser, and somewhat by various simulation setup code. These should be able to give forth the types they themselves create.

There is one exception, which is `Centroid` which checks for `LinkType.DEFAULTS.CONNECTOR`. That default cannot be used when it is returned. I think it is better to add a class `Connector extends OtsLink`, which might check that at least one connected `Node` is a `Centroid`. The `Centroid` class can check for `instanceof Connector`.

So I would suggest:
- No types stored in `OtsNetwork`.
- New `Connector` class.

@averbraeck if you agree, issue #14 can be closed.

**Comment by WJSchakel** [comment]
In `CrossSectionLink` there are three methods `set/clear/getDemandWeight()`. These are good candidates to be moved to `Connector`. Method `setWeight()` also checks whether the link is a connector through `getType().isConnector()`. But `LinkType.isConnector()` will have to be removed when we remove the DEFAULTS. So `Connector` would be a good place for the methods.

**Comment by averbraeck** [comment]
> if you agree, issue https://github.com/averbraeck/opentrafficsim/issues/14 can be closed.

Yes, I agree. I think it is much more elegant than how it is implemented right now. I don't mind the boolean field 'connector', since we indicate therewith on beforehand that a Link can be either a 'normal' Link or a Connector. For me, a Connector always was a special Link, and the new implementation nicely reflects that.

**Comment by averbraeck** [comment]
>  So Connector would be a good place for the methods.

I think so too.

**Comment by WJSchakel** [comment]
`DefaultsNl` now includes default `LinkType`s. `DefaultsRoadNl` contains default `LaneType`s. An instance can be reached at `DefaultsRoad.NL`.

`DefaultsRoad` extends `Defaults`. Through static methods `getByName` defaults may be found. `Defaults` has a protected static helper method such that subclasses can easily find fields in their own class.

- Interface `RoadNetwork` adds noting anymore. `OtsRoadNetwork` already implements `Network` and `PerceivableContext` via `OtsNetwork`. The network inheritance structure is a prime candidate for simplification.
- `TemplateGtuType` is no longer supplied by `Defaults`, it messed with the inheritance structure for defaults towards ots-road. Rather, any appropriate `BiFunction<>` can do this. `DefaultsNl` implements this, and an instance is found under `Defaults.NL`.
- There are no defaults for `NodeType`. There are now two static values `NodeType.NODE` and `NodeType.CENTROID` which are directly used in the `getType()` method of `OtsNode` and `Centroid` respectively. I currently see no use for custom node types.
- `Network` used to be a sub-type of `Definitions`. These two types are now separated, and `Definitions` is used by the XML parser to store and retrieve types. It can store types of any `HierarchicalType`, including `LaneType` from ots-road. Therefore there is  no longer a need for `DefinitionsRoad`, it has been removed.
- XML specifies a speed limits for GTU types under `LINKTYPE`, but in the parser these are incorporated in to a road layout. Should this information become part of `LinkType`?
- `NodeAnimation` and `LinkAnimation` used different scales to stop showing the id. A distinction was made between FREEWAY and others. As there is no access to types there, it has now been defaulted to the FREEWAY value. In the future we may consider giving a "large scale" type to show the ids as is, and to hide it sooner for others.

**Comment by WJSchakel** [comment]
The remaining open issues are covered by issues #12 and #40.
